spring.application.name=KursovayaBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/Route
spring.datasource.username=NewPostgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.kursovayabackend.entity

jwt.secret=Gd5q9S8Vv2yXp7T1wE4rF6uH3jK9mN0oL5iP8qA2sD4f
jwt.expiration=86400